# Generated by Django 2.2.3 on 2019-07-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_game', models.CharField(max_length=120)),
                ('second_game', models.CharField(max_length=120)),
                ('third_game', models.CharField(max_length=120)),
                ('min_rating', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
