# Generated by Django 2.2.3 on 2019-07-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190711_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='firstGame',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='minRating',
            field=models.DecimalField(decimal_places=2, default='75', max_digits=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='secondGame',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='thirdGame',
            field=models.CharField(default='', max_length=120),
        ),
    ]
