# Generated by Django 2.2.3 on 2019-07-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190712_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thirdGame',
            field=models.CharField(default='', max_length=120, null='True'),
        ),
    ]
