# Generated by Django 2.2.3 on 2019-07-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190712_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='firstGame',
            field=models.CharField(blank='True', default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='secondGame',
            field=models.CharField(blank='True', default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='thirdGame',
            field=models.CharField(blank='True', default='', max_length=120),
        ),
    ]
