# Generated by Django 2.2.3 on 2019-07-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190712_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='minRating',
        ),
    ]
