# Generated by Django 2.2.3 on 2019-07-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190714_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='firstGame',
            field=models.CharField(default='', max_length=120),
        ),
    ]
